### ISSUE TITLE
Comparison with react-scroll-parallax

### ISSUE THREAD

**Issue by oyeanuj** [Stanko/react-plx#15]
Hi @Stanko, Thank you for putting out this library, it looks really promising. I am curious, as the author, if you have any thoughts comparing `react-plx` with [`react-scroll-parallax`](https://github.com/jscottsmith/react-scroll-parallax) (the only other library which looked promising)?

Any points of comparison/pros/cons from your point of view would be super helpful in deciding between the two.

**Comment by Stanko** [comment]
Hello @oyeanuj,
Don't take my word for granted, as I just saw `react-scroll-parallax`. Main pros of `Plx` are: 

* `react-plx` has much more flexible configuration (
  * multiple CSS attributes per animations
  * multiple animations on the same element
  * support for colors or any numeric CSS attribte
* scroll handling is more performant
* there is no need to call `.update()` if page changes
* out of the box easing 
* classes based on the animation state

Cons:

* `Plx` is really young, and I have to refactor a lot of props to use element's relative position rather than fixed pixel values (which makes hard to create some effects)

Don't get me wrong, `react-scroll-parallax` seems like a fine library, and if it works for you, don't use it just because mine library has more options (which you might not need at all).

Hope that helps, cheers!
