### ISSUE TITLE
Act only on Sub-Elements of the Parallax

### ISSUE THREAD

**Issue by xstable** [Stanko/react-plx#72]
Is it possible in any way to act only on a Sub-Element inside of the parallax?

Example: 
You have a parallax, where you have an this inside:
```
<div class="testDiv" style='border:10px solid red; min-height:50vh; height: 400px; width:200px'>
<h1>Whats up?</h1>
<p>Nothing at all!</p>
</div>
```
How could I only change the borderColor of this single red div to transparent?
Might there be an parameter like: 
```
"properties":[
          {
            "startValue": "rgba(255,0,0,1)",
            "endValue": "transparent",
            "property": "borderColor"
            "element": ".testDiv"
          },
```
Or is there another way to archive this?

**Comment by Stanko** [comment]
Hello,
I'm not sure if I understood your question. If you want to nest parallaxes, you can put `Plx` inside other `Plx` element:

```jsx
<Plx>
  Content
  <Plx>
    Nested parallax element
  </Plx>
</Plx>
```

If you ask only how to apply border color to the `testDiv` that is exactly what library does. Just replace `div` with `Plx`:

```jsx
<Plx className="testDiv" style="border-color: red;">
  <h1>Whats up?</h1>
  <p>Nothing at all!</p>
</div>
```

If you are passing styles instead of using CSS classes, when `borderColor` make sure you define it as a standalone prop instead of using a shorthand property. Because library will merge styles

Do this:
```html
style="border-width: 10px; border-style: solid; border-color: red;">
```
and not this:
```html
style="border: 10px solid red">
```

Check the demo here https://codesandbox.io/s/react-plx-demo-forked-geyuq?file=/index.js


Additionally as it is noted in the documentation, for colors supported formats are: #123, #001122, rgb(0,0,255) and rgba(0,0,255,0.5).

Hope that helps, cheers!

**Comment by xstable** [comment]
I use Plx inside Gatsby and generated an Dynamic Component.
That Component can wrap PLX around an self defined HTML-Element, or around another component. 
But your hint is awesome. I don't mind that I even can encapsulate multiple Plx within other Plx components. 
Nice.
